myforum/accounts/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from myforum.accounts import views

urlpatterns = [

    # Get the reset/ urls
    path('', views.listing, name="accounts_index"),
    path('admin/', admin.site.urls, name='django_admin'),

    path(r'password/reset/', views.password_reset, name='password_reset'),
    path(r'password/reset/done/', views.password_reset_done, name='password_reset_done'),

    re_path(r'verify/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
            views.email_verify_account, name='email_verify_account'),

    re_path(r'reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
            views.pass_reset_confirm, name='password_reset_confirm'),

    path(r'verify/', views.send_email_verify, name="send_email_verify"),

    path(r'reset/done/', views.password_reset_complete, name='password_reset_complete'),
    path(r'moderate/<str:uid>/', views.user_moderate, name="user_moderate"),
    path(r'login/', views.user_login, name="login"),
    path(r'signup/', views.user_signup, name="signup"),
    path(r'profile/<str:uid>/', views.user_profile, name="user_profile"),

    path(r'edit/profile/', views.edit_profile, name='edit_profile'),
    path(r'toggle/notify/', views.toggle_notify, name='toggle_notify'),
    path(r'logout/', views.user_logout, name="logout"),

    path(r'debug/user/', views.debug_user, name="debug_user"),

    # Message urls
    path(r'inbox/', views.message_list, name='inbox'),

    # External url login
    path(r'external/', views.external_login, name="external"),

    # Used for 3rd party logins.
    path("social/", include('allauth.urls')),



]

myforum/emailer/urls.py
from . import views

from django.urls import path

urlpatterns = [
    path('', views.index, name='emailer-index'),
]

myforum/forum/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path  # For django versions from 2.0 and up
import debug_toolbar
from myforum.forum import views
from myforum.forum import ajax
import myforum.accounts.urls as account_patterns

urlpatterns = [

    # Main entry. Post listing.
    path('', views.latest, name='post_list'),
    path('admin/', admin.site.urls),

    path('policy/', views.policy, name='policy'),

    path('votes/', views.myvotes, name='myvotes'),
    path('bookmarks/', views.bookmarks, name='bookmarks'),
    path('following/', views.following, name='following'),
    path('myposts/', views.myposts, name='myposts'),

    path('p/<str:uid>/', views.post_view, name='post_view'),

    path('new/post/', views.new_post, name='post_create'),
    path('new/comment/<str:uid>/', views.new_comment, name="create_comment"),


    path('b/list/', views.badge_list, name='badge_list'),
    path('t/list/', views.tags_list, name='tags_list'),

    path('b/view/<str:uid>/', views.badge_view, name='badge_view'),
    path('edit/post/<str:uid>/', views.edit_post, name='post_edit'),

    path('ajax/digest/', ajax.ajax_digest, name='ajax_digest'),
    path('ajax/vote/', ajax.ajax_vote, name='vote'),
    path('ajax/test/', ajax.ajax_test, name='ajax_test'),
    path('ajax/search/', ajax.ajax_search, name='ajax_search'),
    path('ajax/tags/search/', ajax.ajax_tags_search, name='ajax_tags_search'),
    path('ajax/subscribe/', ajax.ajax_subs, name='ajax_sub'),


    path('ajax/tags/search/', ajax.ajax_tags_search, name='ajax_tags_search'),
    path('similar/posts/<str:uid>/', ajax.similar_posts, name='similar_posts'),
    path('ajax/digest/<str:uid>/', ajax.ajax_digest, name='ajax_digest'),

    path('ajax/edit/<str:uid>/', ajax.ajax_edit, name='ajax_edit'),
    path('ajax/create/', ajax.ajax_create, name='ajax_create'),
    path('inplace/form/', ajax.inplace_form, name='inplace_form'),

    path('ajax/search/', ajax.ajax_search, name='ajax_search'),

    path('similar/posts/<str:uid>/', ajax.similar_posts, name='similar_posts'),

    path('moderate/<str:uid>/', views.post_moderate, name="post_moderate"),

    # Community urls
    path('community/', views.community_list, name='community_list'),

    # Include the accounts urls
    path('accounts/', include(account_patterns)),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT, show_indexes=True)

    urlpatterns = [
        path(r'__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

myforum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

import myforum.accounts.urls as accounts_urls
import myforum.forum.urls as engine_urls
import myforum.forum.urls as forum_urls

if settings.ENGINE_AS_ROOT:
    engine_url_pattern = r'^'
    forum_url_pattern = r'^forum/'
else:
    engine_url_pattern = r'^projects/'
    forum_url_pattern = r'^'


# Default url patters for the engine.
urlpatterns = [


    # The engine handler.
    url(engine_url_pattern, include(engine_urls)),

    # Forum urls
    url(forum_url_pattern, include(forum_urls)),
    url(r'^accounts/', include(accounts_urls)),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT, show_indexes=True)
    if settings.INTERNAL_IPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

myforum/accounts/models.py
import uuid
from datetime import datetime, timedelta

import mistune
from django.conf import settings
from django.shortcuts import reverse
from django.contrib.auth.models import User
from django.db import models
from django.utils.timezone import utc
from myforum.accounts import util


def fixcase(name):
    return name.upper() if len(name) == 1 else name.lower()


def now():
    return datetime.utcnow().replace(tzinfo=utc)


MAX_UID_LEN = 255
MAX_NAME_LEN = 255
MAX_TEXT_LEN = 10000
MAX_FIELD_LEN = 1024


class Profile(models.Model):
    NEW, TRUSTED, SUSPENDED, BANNED = range(4)
    STATE_CHOICES = [(NEW, "New"), (TRUSTED, "Active"), (SUSPENDED, "Suspended"), (BANNED, "Banned")]
    state = models.IntegerField(default=NEW, choices=STATE_CHOICES, db_index=True)

    READER, MODERATOR, MANAGER, BLOGGER, SPAMMER = range(5)
    ROLE_CHOICES = [
        (READER, "Reader"), (MODERATOR, "Moderator"), (MANAGER, "Admin"),
        (BLOGGER, "Blog User"), (SPAMMER, "Spammer")
    ]

    NO_DIGEST, DAILY_DIGEST, WEEKLY_DIGEST, MONTHLY_DIGEST,ALL_MESSAGES  = range(5)

    DIGEST_CHOICES = [(NO_DIGEST, 'Never'), (DAILY_DIGEST, 'Daily'),
                      (WEEKLY_DIGEST, 'Weekly'), (MONTHLY_DIGEST, 'Monthly'),
                      (ALL_MESSAGES, "Email for every new thread (mailing list mode)")
                      ]
    # Subscription to daily and weekly digests.
    digest_prefs = models.IntegerField(choices=DIGEST_CHOICES, default=WEEKLY_DIGEST)

    LOCAL_MESSAGE, EMAIL_MESSAGE, NO_MESSAGES, DEFAULT_MESSAGES = range(4)
    MESSAGING_TYPE_CHOICES = [
        (DEFAULT_MESSAGES, "Default"),
        (EMAIL_MESSAGE, "Email"),
        (LOCAL_MESSAGE, "Local Messages"),
        (NO_MESSAGES, "No messages"),

    ]
    # Default subscriptions inherit from this
    message_prefs = models.IntegerField(choices=MESSAGING_TYPE_CHOICES, default=DEFAULT_MESSAGES)

    # Connection to the user.
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # User unique id (handle)
    uid = models.CharField(max_length=MAX_UID_LEN, unique=True)

    # User diplay name.
    name = models.CharField(max_length=MAX_NAME_LEN, default='', db_index=True)

    # Maximum amount of uploaded files a user is allowed to aggregate, in mega-bytes.
    max_upload_size = models.IntegerField(default=0)

    # The role of the user.
    role = models.IntegerField(default=READER, choices=ROLE_CHOICES)

    # The date the user last logged in.
    last_login = models.DateTimeField(null=True, max_length=255, db_index=True)

    # The number of new messages for the user.
    new_messages = models.IntegerField(default=0, db_index=True)

    # The last visit by the user.
    date_joined = models.DateTimeField(auto_now_add=True, max_length=255)

    # User provided location.
    location = models.CharField(default="", max_length=255, blank=True, db_index=True)

    # User provided website.
    website = models.URLField(default="", max_length=255, blank=True)

    # Google scholar ID
    scholar = models.CharField(default="", max_length=255, blank=True)

    # User reputation score.
    score = models.IntegerField(default=0, db_index=True)

    # Twitter ID
    twitter = models.CharField(default="", max_length=255, blank=True)

    # This field is used to select content for the user.
    my_tags = models.CharField(default="", max_length=255, blank=True)

    # Description provided by the user html.
    text = models.TextField(default="No profile information", null=True, max_length=MAX_TEXT_LEN, blank=True)

    # The html version of the user information.
    html = models.TextField(null=True, max_length=MAX_TEXT_LEN, blank=True)

    # The state of the user email verfication.
    email_verified = models.BooleanField(default=False)

    # Automatic notification
    notify = models.BooleanField(default=False)

    # Opt-in to all messages from the site
    opt_in = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.uid = self.uid or util.get_uuid(8)
        self.html = self.html or mistune.markdown(self.text)
        self.max_upload_size = self.max_upload_size or settings.MAX_UPLOAD_SIZE
        self.name = self.name or self.user.first_name or self.user.email.split("@")[0]
        self.date_joined = self.date_joined or now()
        self.last_login = self.last_login or now() - timedelta(days=1)
        super(Profile, self).save(*args, **kwargs)

    @property
    def is_moderator(self):
        # Managers can moderate as well.
        return self.role == self.MODERATOR or self.role == self.MANAGER or self.user.is_staff or self.user.is_superuser

    @property
    def trusted(self):
        return (self.user.is_staff or self.state == self.TRUSTED or
                self.role == self.MODERATOR or self.role == self.MANAGER or self.user.is_superuser )

    @property
    def is_manager(self):
        return self.role == self.MANAGER

    def get_absolute_url(self):

        return reverse('user_profile', kwargs=dict(uid=self.uid))

    @property
    def is_suspended(self):
        return self.state == self.SUSPENDED

    @property
    def is_banned(self):
        return self.state == self.BANNED


# Connects user to message bodies
class MessageBody(models.Model):
    """
    A message that may be shared across all users.
    """
    body = models.TextField(max_length=MAX_TEXT_LEN)
    html = models.TextField(default='', max_length=MAX_TEXT_LEN * 10)

    def save(self, *args, **kwargs):
        self.html = self.html or mistune.markdown(self.body)
        super(MessageBody, self).save(**kwargs)


# Connects user to message bodies
class Message(models.Model):
    """
    Connects recipients to sent messages
    """

    SPAM, VALID, UNKNOWN = range(3)
    SPAM_CHOICES = [(SPAM, "Spam"), (VALID, "Not spam"), (UNKNOWN, "Unknown")]
    spam = models.IntegerField(choices=SPAM_CHOICES, default=UNKNOWN)

    uid = models.CharField(max_length=32, unique=True)
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="author", on_delete=models.CASCADE)
    recipient = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    subject = models.CharField(max_length=120)
    body = models.ForeignKey(MessageBody, on_delete=models.CASCADE)

    unread = models.BooleanField(default=True)
    sent_date = models.DateTimeField(db_index=True, null=True)

    def save(self, *args, **kwargs):
        self.uid = self.uid or util.get_uuid(10)
        self.sent_date = self.sent_date or util.now()
        super(Message, self).save(**kwargs)

    def __str__(self):
        return f"Message {self.sender}, {self.recipient}"

myforum/forum/templates/accounts/edit_profile.html
{% extends "forum_base.html" %}
{% load forum_tags %}
{% load accounts_tags %}

{% block headtitle %}Edit Profile{% endblock %}

{% block content %}

   <div class="ui horizontal segments no-shadow">

        <div class="ui segment  no-shadow"></div>
           <div class="ui basic compact segment no-shadow">

    <form method="post" class="ui equal width form" action="{% url 'edit_profile' %}">
        {{ form.media }}
        {% csrf_token %}

        {% form_errors form %}

        <div class="ui basic center aligned segment">
            <span class="ui header">Update Profile</span>
        </div>

        <div class="fields">
            <div class="empty form-field field"></div>

            <div class="required form-field field">
                <div class="ui form-wrap segment">
                <label><i class="address card icon"></i>Name </label>
                {{ form.name }}
                <div class="muted">
                    Displayed name
                </div>
                </div>
            </div>

            <div class="empty form-field field"></div>
        </div>

        <div class="fields">
            <div class="empty form-field field"></div>

            <div class="required form-field field">
                <div class="ui form-wrap segment">
                    <label><i class="envelope card icon"></i>Email </label>
                    {{ form.email }}
                    <div class="muted">
                        Email, not visible to others
                    </div>
                </div>
            </div>

            <div class="empty form-field field"></div>
        </div>

        <div class="fields">
            <div class="empty form-field field"></div>

            <div class="required form-field field">
                <div class="ui form-wrap segment">
                    <label><i class="at icon"></i>Handle</label>
                    {{ form.username }}
                    <div class="muted">
                        Handle may be used to reference you in posts.
                    </div>
                </div>
            </div>

            <div class="empty form-field field"></div>
        </div>


        <div class="fields">

            <div class="field">
                <div class="ui form-wrap segment">
                    <label><i class="linkify icon"></i>Website</label>
                    {{ form.website }}
                    <div class="muted">
                        URL to your website
                    </div>
                </div>
            </div>

            <div class="field">
                <div class="ui form-wrap segment">
                    <label><i class="map marker alternate icon"></i>Location</label>
                    {{ form.location }}
                    <div class="muted">
                        Country/City/Institution
                    </div>
                </div>
            </div>


        </div>


        <div class="fields">
            <div class="field">
                <div class="ui form-wrap segment">

                    <label><i class="twitter icon"></i>Twitter id</label>
                    {{ form.twitter }}
                    <div class="muted">
                        Your twitter id
                    </div>
                </div>
            </div>

            <div class="field">
                <div class="ui form-wrap segment">
                    <label><i class="google icon"></i>Scholar</label>
                    {{ form.scholar }}
                    <div class="muted">
                        Your Google Scholar ID
                    </div>
                </div>
            </div>
        </div>

            <div class="fields">

                    <div class="field">
                        <div class="ui form-wrap segment" style="display: grid">
                        <label><i class="bell icon"></i>Notifications </label>
                        {{ form.message_prefs }}
                        <div class="muted">
                            {{ form.message_prefs.help_text }}
                        </div>
                        </div>
                    </div>

            </div>


        <div class="fields">

            <div class="field">
                <div class="ui form-wrap segment" style="display: grid">
                    <label><i class="info icon"></i>Description</label>
                    {{ form.text }}
                    <div class="muted">
                        {{ form.text.help_text }}
                    </div>
                </div>
            </div>

        </div>

        <button type="submit" class="ui submit green button">
            <i class="save icon"></i>Submit
        </button>

        <a class="ui right floated button" href="{% url "user_profile" user.profile.uid %}">
            <i class="undo icon"></i>Cancel
        </a>



    </form>
   </div>

    <div class="ui segment no-shadow"></div>
</div>


{% endblock %}

myforum/forum/templates/accounts/login.html
{% extends "forum_base.html" %}
{% load forum_tags %}
{% load socialaccount %}
{% block headtitle %}Login{% endblock %}

{% block content %}

    {% if  social_login %}
        <div class="ui segment inputcolor socialbox">
            <div class="ui header">
                <i class="universal access icon"></i> Automatic Login
            </div>

            <p>
                Click the link below to log in or sign up automatically:
            </p>

           <div class="ui large relaxed icon list">
                {% for provider in social_login.iterator %}
                    <a class="item" href="{% provider_login_url provider.provider %}">
                        <i class="{{ provider.name|lower }} large icon"></i>
                        <div class="middle aligned content"> {{ provider.name|title }}</div>

                    </a>
                {% endfor %}
            </div>

            <p>
                Social login is used for authentication only.
            </p>
        </div>
    {% endif %}

    <form class="ui form" method="post" action="{% url 'login' %}">

        <div class="ui segment inputcolor socialbox">

            <div class="ui header">
                <i class="user icon"></i> Email Login
            </div>

            {% csrf_token %}

            {{ form.errors }}
            <div class="field">
                <label>Email</label>
                {{ form.email }}
            </div>

            <div class="field">
                <label>Password</label>
                {{ form.password }}
            </div>

            <div class="field">
                <button class="ui primary button" type="submit">
                    <i class="sign in icon"></i>Log In
                </button>

                <a class="ui right floated button" href="#" onclick="window.history.back()">
                    <i class="chevron left icon"></i>Back
                </a>
            </div>

        </div>


    </form>

    <div class="ui center aligned basic segment">


        <a href="{% url 'password_reset' %}"><i class="question circle icon"></i>Forgot your password?</a>
        &bull; <a class="" href="{% url 'signup' %}"><i class="add user icon"></i>Sign up with email</a>
    </div>




{% endblock %}

myforum/forum/templates/accounts/logout.html
{% extends "forum_base.html" %}
{% load forum_tags %}
{% load accounts_tags %}

{% block headtitle %} myforum Forum {% endblock %}
{% block title %} Log out {% endblock %}

{% block content %}

     <form method="post" action="{% url 'logout' %}" >

        <div class="ui center aligned header">

            <i class="sign out icon"></i>Do you want to log out?

        </div>
        <div class="ui centered card inputcolor">

            <div class="ui basic segment">
                    {% csrf_token %}
                    <button class="ui primary button" type="submit"> <i class="sign out icon"></i> Log out</button>
                    <a class="ui right floated  button" href="/"> <i class="home icon"></i>Home</a>
            </div>
        </div>
 </form>
{% endblock %}

myforum/forum/templates/accounts/password_reset_complete.html
{% extends "forum_base.html" %}
{% block title %} Password Reset Complete{% endblock %}

{% block content %}

  <p class="ui center aligned basic segment">

    Your password has been reset. You may <a href="{% url 'login' %}">sign in</a> now.
  </p>

{% endblock %}

myforum/forum/templates/accounts/password_reset_confirm.html
{% extends "forum_base.html" %}
{% block headtitle %} Reset Password {% endblock %}

{% block content %}

    <div class="ui raised segment">

        <div class="ui center aligned header">

            <i class="user icon"></i>Change password

        </div>
         <div class="ui centered card inputcolor">

            <div class="ui basic segment">
                {% if validlink %}

                    <form method="post" class="ui form attached fluid segment" >
                        {% csrf_token %}
                        <div class="field">
                            <label>New Password</label>
                            {{ form.new_password1 }}
                        </div>

                        <div class="field">
                        <label>New Password Confirmation</label>
                        {{ form.new_password2 }}
                        </div>

                    <button class="ui primary button" type="submit">Change password</button>
                    </form>

                {% else %}
                    <p class="ui center aligned basic segment">

                      The password reset link was invalid, possibly because it has already been used.
                      Please request a new password reset.
                    </p>
                {% endif %}
            </div>
        </div>
    </div>
{%endblock%}

myforum/forum/templates/accounts/password_reset_done.html
{% extends "forum_base.html" %}
{% block headtitle %}Reset Email Sent{% endblock %}

{% block content %}
<div class="ui raised segment">
    <p class="ui center aligned basic segment">

    We've emailed you instructions for setting your password, if an account exists with the email you entered.
    You should receive them shortly.
  </p>
    <p class="ui center aligned basic segment">

    If you don't receive an email, please make sure you've entered the address you registered with,
    and check your spam folder.
  </p>
</div>
{% endblock %}

myforum/forum/templates/accounts/password_reset_form.html
{% extends "forum_base.html" %}
{% block headtitle %} Reset Password {% endblock %}

{% block content %}

        <div class="ui center aligned header">

            <i class="user icon"></i>Password reset

        </div>

        <div class="ui centered card inputcolor">

            <div class="ui basic segment">
                <form class="ui form " method="post">
                    {% csrf_token %}

                    <div class="field">
                        <label>Enter your email</label>

                        {{ form.email }}
                        {{ form.errors }}
                    </div>

                    <div>
                        <button class="ui primary button" type="submit">Send</button>
                        <a class="ui right floated button" href="{%  url "login" %}">
                            <i class="sign in icon"></i>Log in</a>
                    </div>
                </form>
            </div>

        </div>

    <p class="ui center aligned basic segment">

        Enter your email and press <b>Send</b>
        to receive an email with password reset instructions.</p>

{% endblock %}

myforum/forum/templates/accounts/profile_base.html
{% load staticfiles %}
{% load compress %}
{% load accounts_tags %}

{% load recaptcha2 %}

<html>
<head>

    <title>
        {# Page Title #}
        {% block headtitle %}Title{% endblock %}

    </title>

    {# Extra header content #}
    {% block head %}

    {% endblock %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    {% recaptcha_init %}


    {% block js %}
    {% endblock %}

</head>
<body>

        {% block title %}
        {% endblock %}


    {% block menu %}
    {% endblock %}

        {% block body %}
            {# Main body #}
            BODY

            {% block content %}

            {% endblock %}

        {% endblock %}



    {% block footer %}
    {% endblock %}






</body>
</html>

myforum/forum/templates/accounts/user_moderate.html
<div class="ui left aligned segment inputcolor">

    <h5>Moderating: @{{target.username}}</h5>

    <form method="post" class="ui form" action="{%  url 'user_moderate' target.profile.uid %}">

        {% csrf_token %}

        <div class="ui segment">
            {{form.action}}
        </div>

        <button type="submit" class="ui blue mini button">
            <i class="check icon"></i>
            Submit
        </button>

        <a class="ui orange right floated mini button" onclick="javascript:obj=$('#modpanel').remove();">
            <i class="cancel icon"></i>
            Cancel
        </a>
    </form>

</div>

myforum/forum/templates/accounts/user_profile.html
{% extends "forum_base.html" %}
{% load accounts_tags %}
{% load forum_tags %}
{% block headtitle %}{{ target.profile.name }}{% endblock %}

{% block content %}

    <div class="ui stackable three column grid">

        <div class="column">


            <div class="ui center aligned  basic segment">
                <img class="ui centered circular image" src="{% gravatar user=target size=150 %}">
                 <div class="ui centered header">
                            {{ target.profile.name }}
                            {% user_icon user=target %}
                </div>
            </div>

            <div class="ui center aligned  basic segment">

                {% if target == request.user %}
                    <a class="ui mini button" href="{% url 'edit_profile' %}">
                        <i class="write icon"></i>Edit profile
                    </a>
                {% endif %}

                {% if can_moderate %}
                    <div class="ui mini button orange moderate-user" data-value="{{ target.profile.uid }}">
                        <i class="hand paper icon"></i>
                        Moderate
                    </div>
                {% endif %}

                {% if request.user.is_superuser and debugging %}
                    <a class="ui mini red button" href="{% url 'debug_user' %}?uid={{ target.profile.uid }}">
                        <i class="sign in icon"></i> Log in
                    </a>
                {% endif %}

            </div>

            <div id="moderate-insert-{{ target.profile.uid }}"></div>
        </div>

        <div class="column">


            <div class="ui center aligned basic segment">



                <table class="ui very basic table profile">
                    <tbody>



                    {% if target.profile.is_moderator %}
                        <tr>
                            <td>Role:</td>
                            <td>{{ target.profile.get_role_display }}</td>
                        </tr>
                    {% endif %}

                    <tr>
                        <td>Status:</td>
                        <td>{{ target.profile.get_state_display }}</td>
                    </tr>

                    <tr>
                        <td>Handle:</td>
                        <td> <code>@{{ target.username }}</code></td>
                    </tr>

                    <tr>
                        <td>Status:</td>
                        <td>{{ target.profile.get_state_display }}</td>
                    </tr>

                    <tr>
                        <td>Reputation:</td>
                        <td>{% user_score user=target %}</td>
                    </tr>

                    <tr>
                        <td>Email:</td>
                        <td>{{ target|show_email:request.user }}</td>
                    </tr>

                    <tr>
                        <td>Joined:</td>
                        <td>{{ target.profile.date_joined|time_ago }}</td>
                    </tr>

                     {% if target.profile.twitter %}
                        <tr>
                            <td>Twitter:</td>
                            <td>
                                <a href="https://twitter.com/{{ target.profile.twitter }}"><i class="twitter icon"></i>{{ target.profile.twitter }}</a>
                            </td>
                        </tr>
                    {% endif %}

                     {% if target.profile.scholar %}
                        <tr>
                            <td>Google Scholar:</td>
                            <td>
                                <a href="https://scholar.google.com/citations?user={{ target.profile.scholar }}"><i class="book icon"></i>{{ target.profile.scholar }}</a>
                            </td>
                        </tr>
                    {% endif %}

                    <tr>
                        <td>Last seen:</td>
                        <td>{{ target.profile.last_login |time_ago }}</td>
                    </tr>

                    <tr>
                        <td>Location:</td>
                        <td>{{ target.profile.location }}</td>
                    </tr>

                    </tbody>
                </table>

            </div>


        </div>
        <div class="column">
            <div class="profile ui relaxed divided list profile">

                <div class="item">
                    <div class="content">
                        {% if target.profile.is_banned or target.profile.is_suspended %}
                            No profile information.
                        {% else %}
                            <p>{{ target.profile.html |safe }}</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

        <div class="ui vertical segment">

        <div class="ui top attached tabular  menu">

            <a class="{% activate 'posts' active %}  item" href="{% url 'user_profile' target.profile.uid %}?active=posts">
                <i class="list alternate outline icon"></i><span class="phone"> Posts</span>
            </a>

            <a class="{% activate 'awards' active %}  item" href="{% url 'user_profile' target.profile.uid %}?active=awards">
                <i class="star outline icon"></i><span class="phone">Awards</span>
            </a>

        </div>
         <div class="ui bottom attached profile segment">
        {% if active == 'posts' %}
            {% list_posts target=target %}
        {% else %}
            {% list_awards target=target %}
        {% endif %}
         </div>
    </div>

{% endblock %}