myforum/accounts/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from myforum.accounts import views

urlpatterns = [

    # Get the reset/ urls
    path('', views.listing, name="accounts_index"),
    path('admin/', admin.site.urls, name='django_admin'),

    path(r'password/reset/', views.password_reset, name='password_reset'),
    path(r'password/reset/done/', views.password_reset_done, name='password_reset_done'),

    re_path(r'verify/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
            views.email_verify_account, name='email_verify_account'),

    re_path(r'reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
            views.pass_reset_confirm, name='password_reset_confirm'),

    path(r'verify/', views.send_email_verify, name="send_email_verify"),

    path(r'reset/done/', views.password_reset_complete, name='password_reset_complete'),
    path(r'moderate/<str:uid>/', views.user_moderate, name="user_moderate"),
    path(r'login/', views.user_login, name="login"),
    path(r'signup/', views.user_signup, name="signup"),
    path(r'profile/<str:uid>/', views.user_profile, name="user_profile"),

    path(r'edit/profile/', views.edit_profile, name='edit_profile'),
    path(r'toggle/notify/', views.toggle_notify, name='toggle_notify'),
    path(r'logout/', views.user_logout, name="logout"),

    path(r'debug/user/', views.debug_user, name="debug_user"),

    # Message urls
    path(r'inbox/', views.message_list, name='inbox'),

    # External url login
    path(r'external/', views.external_login, name="external"),

    # Used for 3rd party logins.
    path("social/", include('allauth.urls')),



]

myforum/emailer/urls.py
from . import views

from django.urls import path

urlpatterns = [
    path('', views.index, name='emailer-index'),
]

myforum/forum/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path  # For django versions from 2.0 and up
import debug_toolbar
from myforum.forum import views
from myforum.forum import ajax
import myforum.accounts.urls as account_patterns

urlpatterns = [

    # Main entry. Post listing.
    path('', views.latest, name='post_list'),
    path('admin/', admin.site.urls),

    path('policy/', views.policy, name='policy'),

    path('votes/', views.myvotes, name='myvotes'),
    path('bookmarks/', views.bookmarks, name='bookmarks'),
    path('following/', views.following, name='following'),
    path('myposts/', views.myposts, name='myposts'),

    path('p/<str:uid>/', views.post_view, name='post_view'),

    path('new/post/', views.new_post, name='post_create'),
    path('new/comment/<str:uid>/', views.new_comment, name="create_comment"),


    path('b/list/', views.badge_list, name='badge_list'),
    path('t/list/', views.tags_list, name='tags_list'),

    path('b/view/<str:uid>/', views.badge_view, name='badge_view'),
    path('edit/post/<str:uid>/', views.edit_post, name='post_edit'),

    path('ajax/digest/', ajax.ajax_digest, name='ajax_digest'),
    path('ajax/vote/', ajax.ajax_vote, name='vote'),
    path('ajax/test/', ajax.ajax_test, name='ajax_test'),
    path('ajax/search/', ajax.ajax_search, name='ajax_search'),
    path('ajax/tags/search/', ajax.ajax_tags_search, name='ajax_tags_search'),
    path('ajax/subscribe/', ajax.ajax_subs, name='ajax_sub'),


    path('ajax/tags/search/', ajax.ajax_tags_search, name='ajax_tags_search'),
    path('similar/posts/<str:uid>/', ajax.similar_posts, name='similar_posts'),
    path('ajax/digest/<str:uid>/', ajax.ajax_digest, name='ajax_digest'),

    path('ajax/edit/<str:uid>/', ajax.ajax_edit, name='ajax_edit'),
    path('ajax/create/', ajax.ajax_create, name='ajax_create'),
    path('inplace/form/', ajax.inplace_form, name='inplace_form'),

    path('ajax/search/', ajax.ajax_search, name='ajax_search'),

    path('similar/posts/<str:uid>/', ajax.similar_posts, name='similar_posts'),

    path('moderate/<str:uid>/', views.post_moderate, name="post_moderate"),

    # Community urls
    path('community/', views.community_list, name='community_list'),

    # Include the accounts urls
    path('accounts/', include(account_patterns)),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT, show_indexes=True)

    urlpatterns = [
        path(r'__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

myforum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

import myforum.accounts.urls as accounts_urls
import myforum.forum.urls as engine_urls
import myforum.forum.urls as forum_urls

if settings.ENGINE_AS_ROOT:
    engine_url_pattern = r'^'
    forum_url_pattern = r'^forum/'
else:
    engine_url_pattern = r'^projects/'
    forum_url_pattern = r'^'


# Default url patters for the engine.
urlpatterns = [


    # The engine handler.
    url(engine_url_pattern, include(engine_urls)),

    # Forum urls
    url(forum_url_pattern, include(forum_urls)),
    url(r'^accounts/', include(accounts_urls)),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT, show_indexes=True)
    if settings.INTERNAL_IPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

myforum/transfer/models.py
from django.db import models


class Manager(models.Manager):

    def get_queryset(self):
        """
        Route all queries to myforum2 database
        """
        return super().get_queryset().using("myforum2")


class UsersProfile(models.Model):
    website = models.CharField(max_length=255)
    info = models.TextField(blank=True, null=True)
    user_id = models.IntegerField(unique=True)
    uuid = models.CharField(unique=True, max_length=255)
    digest_prefs = models.IntegerField()
    opt_in = models.BooleanField()
    twitter_id = models.CharField(max_length=255)
    my_tags = models.TextField()
    flag = models.IntegerField()
    last_login = models.DateTimeField()
    location = models.CharField(max_length=255)
    watched_tags = models.CharField(max_length=100)
    message_prefs = models.IntegerField()
    scholar = models.CharField(max_length=255)
    id = models.IntegerField(primary_key=True)  # AutoField?
    date_joined = models.DateTimeField()

    objects = Manager()

    class Meta:
        managed = False
        db_table = 'users_profile'


class UsersUser(models.Model):
    status = models.IntegerField()
    is_staff = models.BooleanField()
    name = models.CharField(max_length=255)
    site_id = models.IntegerField(blank=True, null=True)
    is_active = models.BooleanField()
    id = models.IntegerField(primary_key=True)  # AutoField?
    score = models.IntegerField()
    last_login = models.DateTimeField()
    new_messages = models.IntegerField()
    activity = models.IntegerField()
    is_admin = models.BooleanField()
    password = models.CharField(max_length=128)
    type = models.IntegerField()
    email = models.CharField(unique=True, max_length=255)
    badges = models.IntegerField()
    flair = models.CharField(max_length=15)

    objects = Manager()

    class Meta:
        managed = False
        db_table = 'users_user'

    @property
    def profile(self):
        return UsersProfile.objects.filter(user_id=self.id).first()


class PostsPost(models.Model):
    site_id = models.IntegerField(blank=True, null=True)
    rank = models.FloatField()
    creation_date = models.DateTimeField()
    reply_count = models.IntegerField()
    tag_val = models.CharField(max_length=100)
    id = models.IntegerField(primary_key=True)
    view_count = models.IntegerField()
    thread_score = models.IntegerField()
    title = models.CharField(max_length=200)
    has_accepted = models.BooleanField()
    vote_count = models.IntegerField()
    content = models.TextField()
    parent_id = models.IntegerField(blank=True, null=True)
    comment_count = models.IntegerField()
    html = models.TextField()
    type = models.IntegerField()
    status = models.IntegerField()
    book_count = models.IntegerField()
    root_id = models.IntegerField(blank=True, null=True)
    lastedit_user_id = models.IntegerField()
    sticky = models.BooleanField()
    lastedit_date = models.DateTimeField()
    changed = models.BooleanField()
    subs_count = models.IntegerField()
    author_id = models.IntegerField()

    objects = Manager()

    class Meta:
        managed = False
        db_table = 'posts_post'

    @property
    def parent(self):
        return self.objects.filter(id=self.parent_id).first()

    @property
    def root(self):
        return self.objects.filter(id=self.root_id).first()

    @property
    def author(self):
        return UsersUser.objects.filter(id=self.author_id).first()

    @property
    def lastedit_user(self):
        return UsersUser.objects.filter(id=self.lastedit_user_id).first()


class PostsSubscription(models.Model):
    id = models.IntegerField(primary_key=True)
    user_id = models.IntegerField()
    post_id = models.IntegerField()
    type = models.IntegerField()
    date = models.DateTimeField()

    objects = Manager()

    class Meta:
        managed = False
        db_table = 'posts_subscription'
        unique_together = (('user_id', 'post_id'),)

    @property
    def user(self):
        return UsersUser.objects.filter(id=self.user_id).first()

    @property
    def post(self):
        return PostsPost.objects.filter(id=self.post_id).first()


class PostsVote(models.Model):
    id = models.IntegerField(primary_key=True)
    author_id = models.IntegerField()
    post_id = models.IntegerField()
    type = models.IntegerField()
    date = models.DateTimeField()

    objects = Manager()

    class Meta:
        managed = False
        db_table = 'posts_vote'

    @property
    def author(self):
        return UsersUser.objects.filter(id=self.author_id).first()

    @property
    def post(self):
        return PostsPost.objects.filter(id=self.post_id).first()


class BadgesBadge(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=50)
    type = models.IntegerField()
    unique = models.BooleanField()
    count = models.IntegerField()
    desc = models.CharField(max_length=200)
    icon = models.CharField(max_length=250)

    objects = Manager()

    class Meta:
        managed = False
        db_table = 'badges_badge'


class BadgesAward(models.Model):
    badge_id = models.IntegerField()
    user_id = models.IntegerField()
    date = models.DateTimeField()
    context = models.CharField(max_length=1000)

    objects = Manager()

    class Meta:
        managed = False
        db_table = 'badges_award'

    @property
    def badge(self):
        return BadgesBadge.objects.filter(id=self.badge_id).first()

myforum/forum/templates/widgets/edit_toplevel.html
{% load forum_tags %}
{% load staticfiles %}

{% if not_trusted %}
    <script src='https://www.google.com/recaptcha/api.js?onload=captchaWidgetId&render=explicit' async defer></script>
{% endif %}

<link rel="stylesheet" type="text/css" href="{% static 'pagedown/demo/browser/demo.css' %}" />
<script type="text/javascript" src="{% static 'pagedown/Markdown.Converter.js' %}"></script>
<script type="text/javascript" src="{% static 'pagedown/Markdown.Sanitizer.js' %}"></script>
<script type="text/javascript" src="{% static 'pagedown/Markdown.Editor.js' %}"></script>


<div class="ui inplace post-form basic segment">

    <form class="ui inplace edit-form compact form" id="post-form">

        <div class="inplace-fields">

            <div class="three wide field type-field">
                {% if not post %}<label>Type</label> {% endif %}
                {% inplace_type_field post=post %}
            </div>

            <div class="field title-field">
            {% if not post %}<label>Title</label> {% endif %}
            <textarea id="title" rows="1">{{ title }}</textarea>
            </div>
        </div>

        <div class="field">
        {% if not post %}
            {% include 'widgets/posting_msg.html' %}
        {% endif %}
        <div id="wmd-button-bar"></div>
            <textarea id="wmd-input" class="wmd-input" rows="{{ rows }}">{{ content }}</textarea>
        </div>


        <div class="field">
        {% if not post %}<label>Tags</label> {% endif %}
            {% get_tags post=post as tags %}
            <input type="hidden" name="tag_val" id="tag_val_id" value="{{ tags.selected }}">

            <select multiple="multiple" class="ui search selection dropdown tag-field" id="tags" field_id="tag_val_id">
                {% for value, selected_tag in tags.tags_opt %}
                    {% if selected_tag %}
                        <option value="{{ value }}" selected="selected">{{ value }}</option>
                    {% else %}
                        <option value="{{ value }}">{{ value }}</option>
                    {% endif %}
                {% endfor %}
            </select>
        </div>

        {% if not_trusted %}
            <div class="required field">
                <div id="captcha"></div>
            </div>
        {% endif %}

        <p class="muted" style="font-size: smaller;">Tips: CTRL+ENTER to submit the form. ESC to
            cancel. Double-click to edit post. Markdown accepted.
        </p>

        <div id="preview">
            <div class="ui preview segment">
                <div id="wmd-preview" class="wmd-panel wmd-preview">{{ content }}</div>
            </div>
        </div>
            <div class="field inplace-buttons">

            <a class="ui green label save" id="save"><i class="check icon"></i>
                {% if post %}
                Save
                {% else %}
                Create
                {% endif %}
            </a>

            <a class="ui label show-preview">
                <i class="code icon"></i>Toggle preview
            </a>

            <a class="ui label cancel" id="cancel"><i class="undo icon"></i> Cancel</a>

        </div>

    </form>

</div>

<script>

    var converter = Markdown.getSanitizingConverter();
    var editor = new Markdown.Editor(converter);
    editor.run();

    var preview =  $('#wmd-preview');
    preview.find('pre').addClass('language-bash');
    preview.find('code').addClass('language-bash');


    $('#wmd-button-bar').click(function () {
        setTimeout(function() {
                    var container = $('#wmd-preview');
                    //alert('ffffff');
                    container.find('pre').addClass('language-bash');
                    container.find('code').addClass('language-bash');
                    Prism.highlightAll();
        }, 10)

    });

    $('.ui.dropdown').dropdown();
    {% if not_trusted %}
        var captchaWidgetId = grecaptcha.render( 'captcha', {
            'sitekey' : '{{ captcha_key }}',
            'theme' : 'light'
        });
    {% endif %}

    function create_toplevel(){
        var create_url = '/ajax/create/';
        // Get the fields to submit
        var title = $('#title');
        var form_elem = $('#post-form');
        var content = $('#wmd-input');
        var post_type = $('#type').dropdown('get value');
        var tag_val = $('#tags').dropdown('get value');
        {% if not_trusted %}
            var cap_response = grecaptcha.getResponse(captchaWidgetId);
        {% else %}
            var cap_response = '';
        {% endif %}

        $.ajax(create_url,
            {
                type: 'POST',
                dataType: 'json',
                ContentType: 'html',
                traditional: true,
                data: {
                    'content': content.val(),
                    'title': title.val(),
                    'type': post_type,
                    'tag_val': tag_val,
                    'top_level':1,
                    'recaptcha_response': cap_response,

                },
                success: function (data) {
                    if (data.status === 'error') {
                        popup_message(form_elem, data.msg, data.status, 3000);
                    } else {
                        //alert(data.redirect);
                        // Redirect user to the new post view.
                        window.location.replace(data.redirect);
                    }
                },
                error: function (xhr, status, text) {
                    error_message(form_elem, xhr, status, text)
                }
            })
    }

    function create_or_edit(){
        {% if post %}
            edit_post("{{ post.uid }}");
        {% else %}
            create_toplevel();
        {% endif %}
    }

    $('#post-form .save').click(function(){
        event.preventDefault();
        create_or_edit();
     });

    $('.tag-field').dropdown({
        allowAdditions: true,
        onChange: function (value, text, $selectedItem) {
            // Get form field to add to
            var tagid = $("#tags").attr('field_id');
            var tag_field = $('#{0}'.f(tagid));
            // Add selected tag to field
            //alert(value);
            tag_field.val(value);
        }
    });

    $('.tag-field >input.search').keydown(function (event) {
        //event.stopPropagation();
        // Prevent submitting form when adding tag by pressing ENTER.
        if (event.keyCode === 13) {
            event.preventDefault();
            //event.stopPropagation();
        }
        // Set value with SPACE bar
        if (event.keyCode === 32) {
            event.preventDefault();
            //event.stopPropagation();
            $("#tags").dropdown('set selected', $(this).val().trim());
            $(this).val('')
        }

    });

    $('#wmd-input').keyup(function (event) {
        // Submit form with CTRL-ENTER
        if (event.ctrlKey && (event.keyCode === 13 || event.keyCode === 10)) {
            create_or_edit()
        }
    })
</script>

myforum/forum/templates/widgets/form_errors.html
{% if errorlist %}

    <div id="form-errors">
        {% for label, message, field_id in errorlist %}
            <div class="error" data-value="#{{ field_id }}" label="{{ label }}" message="{{ message }}"></div>
        {% endfor %}
    </div>

{% endif %}

myforum/forum/templates/widgets/list_awards.html
{% load forum_tags %}

<div class="center-text">
    {% pages objs=awards %}
</div>

{% if awards %}
<div class="ui grid">
    {% for award in awards %}
        <div class="five wide column">
            {% if avatar %}
                <div class="center aligned author">
                    <a href="{% url "user_profile" award.user.profile.uid %}">
                        <div class="ui circular image">
                            <img class="ui centered image" src="{% gravatar user=award.user size=80 %}">
                        </div>
                    </a>
                </div>
            {% endif %}

            <span>
                <a href="{% url 'badge_view' award.badge.uid %}">{{ award.badge.name }}
                <i class="{{ award.badge.icon }}"></i>
                </a>
            </span>
            <span class="muted">
                {{ award.date|timesince }},
            </span>

            {{ award.badge.desc }}.

            {{ award|get_award_context|safe }}
        </div>
     {% endfor %}
</div>
    
{% else %}
    <div class="ui warn message">
        No awards found.
    </div>
{% endif %}


<div class="center-text">
    {% pages objs=awards %}
</div>

myforum/forum/templates/widgets/listing.html
{% load forum_tags %}
{% load accounts_tags %}

<div class="ui divided items">

    {% if include_pages_bar %}
        <div class="ui horizontal basic top-menu segments">
            <div class="ui page-bar segment">
                {% pages objs=posts %}
            </div>
        </div>
    {% endif %}
    {% for post in posts %}

        <div class="post item {{ post.css }} top-padding">

            <div class="statbox">
                <div class="ui left stat label mini">
                    <div class="number-stat">
                        {{ post.get_votecount }}
                    </div>
                    <div class="detail-stat">Vote{{ post.get_votecount|pluralize }}</div>
                </div>
                <div class="ui label stat mini {% boxclass post %}">
                    <div class="number-stat">
                        {{ post.reply_count }}
                    </div>
                    <div class="detail-stat">Repl{{ post.reply_count|pluralize:"y,ies" }}</div>
                </div>

                <div class="ui label basic transparent stat mini">
                    <div class="number-stat">
                        {{ post.root.view_count|bignum }}
                    </div>
                    <div class="detail-stat">View{{ post.root.view_count|pluralize }}</div>
                </div>
                {% if show_subs %}
                    {% subscription_label post.subs_count %}
                {% endif %}
            </div>

            <div class="content">

                <div class="header">
                    {% if not post.is_open %}
                        <span class="ui title header">{{ post.get_status_display }}:</span>
                    {% elif post.type != post.QUESTION %}
                        <span class="ui title header">{{ post.get_type_display }}:</span>
                    {% endif %}

                    <a href="{% url 'post_view' post.uid %}{% if not post.is_toplevel %}#{{ post.uid }}{% endif %}"
                       class="ui mini blue title header ">{{ post.title|truncatechars:150 }}
                    </a>
                </div>

                <div class="right floated">
                    {% get_thread_users post=post as extra_users %}
                    {% for extra_user in extra_users %}
                        <a class="ui mini avatar list-avatar image"
                           href="{% url "user_profile" extra_user.profile.uid %}">
                            <img src="{% gravatar user=extra_user size=90 %}">
                        </a>
                    {% endfor %}

                </div>

                <div class="extra right floated">

                    <div class="left floated">
                        {% post_tags post %}
                    </div>

                    <div class="right floated">

                        {% post_user_line post %}
                    </div>

                </div>

            </div>
        </div>
    {% empty %}
        <div class="ui warn message">

            No posts found.

        </div>
    {% endfor %}

    {% if include_pages_bar %}
        <div class="ui horizontal basic top-menu segments">
            <div class="ui page-bar segment">
                {% pages objs=posts %}
            </div>
        </div>
    {% endif %}

</div>

myforum/forum/templates/widgets/menu-header.html
{% load forum_tags %}
{% load staticfiles %}

<div class="ui labeled icon attached pointing menu" id="menu-header" user-id="{{ request.user.id }}">

    {% block headimg %}
        <div class="header item" id="logo">
            <a href="/"><img class="ui image"  src="{% static "images/prodapt.png" %}"></a>
        </div>
    {% endblock %}

    <a class="item {% activate tab "latest" %}" href="{% url 'post_list' %}">
    <i class="list icon"></i> <span class="tablet">Latest</span>
    </a>
    <a class="item {% activate tab "news" %}" href="{% url 'post_list' %}?type=news">
    <i class="newspaper icon"></i> <span class="tablet">News</span>
    </a>
    <a class="item phone {% activate tab "job" %}" href="{% url 'post_list' %}?type=job">
    <i class="briefcase icon"></i> <span class="tablet">Jobs</span>
    </a>

    <a class="item phone {% activate tab "tutorial" %}" href="{% url 'post_list' %}?type=tutorial">
    <i class="info circle icon"></i> <span class="tablet">Tutorials</span>
    </a>

    <a class="item phone {% activate tab "tags" %}" href="{% url 'tags_list' %}">
        <i class="tag icon"></i> <span class="tablet">Tags</span>
    </a>

    <a class="item {% activate tab "community" %}" href="{% url 'community_list' %}">
        <i class="world icon"></i>
        <span class="tablet">Users</span>
    </a>

     <a class="item {% activate tab "new" %}" id="new-post">
        <i class="edit icon"></i>
        <span class="tablet">New Post</span>
     </a>


</div>

myforum/forum/templates/widgets/pages.html
{% load forum_tags %}
{% load humanize %}

{% if objs.has_previous %}
    <a class="ui small basic button no-shadow" href="{{ url }}{% relative_url objs.previous_page_number 'page' request.GET.urlencode %}">
            <i class="ui angle  double left icon"> </i>
    </a>
{% else %}

<div class="ui small basic button no-shadow">

        <i class="ui angle double left icon"> </i>

</div>
{% endif %}


    <span class="phone">{{objs.paginator.count|intcomma}}
    result{{objs.paginator.count|pluralize}}
    &bull;

        Page </span> {{ objs.number }} of {{ objs.paginator.num_pages }}




{% if objs.has_next %}

<a class="ui small basic button no-shadow" href="{{ url }}{% relative_url objs.next_page_number 'page' request.GET.urlencode %}">

        <i class="ui angle  double right icon"></i>
</a>

{% else %}

<div class="ui small basic button no-shadow">

     <i class="ui angle  double right icon"></i>

</div>

{% endif %}

myforum/forum/templates/widgets/policy.html
{% extends "forum_base.html" %}

{% block content %}

<h2>Policy</h2>

<h3>User agreement</h3>

<p>Be well, do good work and keep in touch.</p>

<h3>Privay policy</h3>

<p>We do not give out or sell your information (including name and email address) to anyone.&nbsp;</p>

<h3>Cookies</h3>

<p>The site will set session cookies whenever you visit the site.
    If you do not intend to ever log in, you may deny this
    cookie, but you cannot log in without it.&nbsp;
    <span style="line-height:1.6">Cookies may be also set when you log in, to be able to
        display new posts and messages that you may have received.
        Cookies may also be set by Google or other companies that help us aggregate
        visitor statistics, traffic and other information.</span>
</p>

{% endblock %}

myforum/forum/templates/widgets/post_actions.html
{% load humanize %}
{% load forum_tags %}

{#  Post action bar. #}


<div class="actions">

    <a class="add-comment ui tiny label" data-value="{{ post.uid }}">{{ label }}</a>

    &bull; <a href="{% url 'post_view' post.root.uid %}#{{ post.uid }}">link</a>

        {% if post.is_editable %}
            &bull; <a class="inplace-click pointer" data-value="{{ post.uid }}">edit</a>
        {% endif %}

        {% if post.can_moderate %}
            &bull; <a class="moderate-post" href="#" data-value="{{ post.uid }}">moderate</a>
        {% endif %}

        {#  Show title on top level posts #}
        {% if post.is_toplevel and user.is_authenticated %}
                        &bull;
            <div class="ui bottom pointing dropdown" id="subscribe" data-uid="{{ post.uid }}">
            <div class="text" id="sub-active">{% follow_label post=post %}</div>
            <i class="caret up icon"></i>
            <div class="menu">
                <div class="item" data-value="messages"><i class="envelope icon"></i>follow via messages </div>
                <div class="item" data-value="email"><i class="envelope outline icon"></i> follow via email</div>
                <div class="item" data-value="unfollow"><i class="close icon"></i> stop following</div>
            </div>
        </div>
        {% endif %}

    <span class="status muted">
        {% post_user_line post=post avatar=avatar %}
    </span>

</div>

myforum/forum/templates/widgets/post_tags.html
{% load forum_tags %}
<div class="tags">
    {% for tag in tags %}
        <a class="ui small label tags" href="{% url 'post_list' %}?tag={{ tag }}">
            {{ tag }}
        </a>
    {% endfor %}
    {% if show_views %}
        &bull; {{ post.root.view_count|bignum }} views
    {% endif %}
</div>

myforum/forum/templates/widgets/post_user_box.html
{% load accounts_tags %}
{% load humanize %}
{% load forum_tags %}

<div class="user_box right">

    <div>
        <a href="{% url "user_profile" user.profile.uid %}">
            <img class="ui centered circular image" src="{% gravatar user=user size=100 %}">
        </a>
    </div>
    <div class="muted">
        {{ post.lastedit_date|time_ago }}<br>

        <a href="{% url "user_profile" user.profile.uid %}">{{ user.profile.name }}</a>
        {% user_icon user=user %}<br>

        {{ user.profile.location }}
    </div>

</div>

myforum/forum/templates/widgets/post_user_line.html
{% load humanize %}
{% load forum_tags %}

{% if post.author.id != post.lastedit_user.id %}

    {{ post.creation_date|time_ago }}
    <a href="{% url "user_profile"  post.author.profile.uid %}">
        {% if avatar %}
            <div class="ui avatar image">
                <img class="ui tiny centered image" src="{% gravatar user=post.author size=80 %}">
            </div>
        {% endif %}
        {{ post.author.profile.name }}
    </a>

    {% user_icon user=post.author %}
    &bull;
    updated

    {{ post.lastedit_date|time_ago }}
    <a href="{% url "user_profile"  post.lastedit_user.profile.uid %}">
        {% if avatar %}
            <div class="ui avatar image">
                <img class="ui tiny centered image" src="{% gravatar user=post.lastedit_user size=80 %}">
            </div>
        {% endif %}
        {{ post.lastedit_user.profile.name }}
    </a>

    {% user_icon user=post.lastedit_user %}

{% elif post %}


    {{ post.lastedit_date|time_ago }}
    <a href="{% url "user_profile"  post.lastedit_user.profile.uid %}">
        {% if avatar %}
            <div class="ui avatar image">
                <img class="ui tiny centered image" src="{% gravatar user=post.lastedit_user size=80 %}">
            </div>
        {% endif %}
        {{ post.lastedit_user.profile.name }}
    </a>

    {% user_icon user=post.lastedit_user %}

{% endif %}